services:
  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      - wordpress
    build:
      context: .
      dockerfile: ./services/nginx/Dockerfile
    restart: unless-stopped
    ports:
      - "443:443"
    extra_hosts:
      - "ftroiter.42.pt:127.0.0.1"
    volumes:
      - ./services/nginx/config:/etc/nginx/http.d/:rw
      - wordpress:/var/www/
    networks:
      - internal

  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: .
      dockerfile: ./services/mariadb/Dockerfile
    env_file: .env
    secrets:
      - db_user_password
      - db_root_password
    restart: unless-stopped
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - internal

  wordpress:
    image: wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    build: 
      context: .
      dockerfile: ./services/wordpress/Dockerfile
      args:
        PHPVERSION: 82
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_HOST: ${DB_HOST}
    restart: unless-stopped
    env_file: .env
    secrets:
      - db_user_password
      - db_username
    volumes:
      - wordpress:/var/www/
    networks:
      - internal

  adminer:
    image: adminer
    container_name: adminer
    depends_on:
      - mariadb
    build:
      context: .
      dockerfile: ./services/bonus/adminer/Dockerfile
      args:
        PHPVERSION: 82
    ports:
      - 8080:8080
    restart: unless-stopped
    networks:
      - internal

volumes:
  database_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/facu/data/database_data
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/facu/data/wordpress

networks:
  internal:
    name: internal
    driver: bridge

secrets:
  db_user_password:
    file: ../secrets/user_password.txt
  db_root_password:
    file: ../secrets/root_password.txt
  db_username:
    file: ../secrets/username.txt