services:
  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      - wordpress
    build: ./services/nginx
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/
    networks:
      - internal

  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./services/mariadb
    env_file: .env
    secrets:
      - db_user_password
      - db_root_password
    restart: unless-stopped
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - internal

  wordpress:
    image: wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    build: 
      context: ./services/wordpress
      args:
        PHPVERSION: 82
    restart: unless-stopped
    env_file: .env
    volumes:
      - wordpress:/var/www/
    networks:
      - internal
    secrets:
      - db_user_password
      - db_username

  redis:
    image: redis
    container_name: redis
    build: ./services/bonus/redis
    ports:
      - 6379:6379
    restart: unless-stopped
    networks:
      - internal
  
  adminer:
    image: adminer
    container_name: adminer
    depends_on:
      - mariadb
    build:
      context: .
      dockerfile: ./services/bonus/adminer/Dockerfile
      args:
        PHPVERSION: 82
    ports:
      - 8080:8080
    restart: unless-stopped
    networks:
      - internal

  vsftpd:
    image: vsftpd
    container_name: vsftpd
    build: ./services/bonus/vsftpd
    ports:
      - 21:21
      - 21000-21010:21000-21010
    volumes:
      - wordpress:/var/www/
    restart: unless-stopped
    networks:
      - internal
    secrets:
      - ftp_username
      - ftp_password

  jekyll:
    image: jekyll/jekyll
    container_name: jekyll
    build: ./services/bonus/jekyll
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - jekyll:/var/www/jekyll
    networks:
      - internal

volumes:
  database_data:
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${HOME}/data/database_data
  wordpress:
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${HOME}/data/wordpress
  jekyll:
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${HOME}/data/jekyll

networks:
  internal:
    name: internal
    driver: bridge

secrets:
  db_user_password:
    file: ../secrets/user_password.txt
  db_root_password:
    file: ../secrets/root_password.txt
  db_username:
    file: ../secrets/username.txt
  ftp_username:
    file: ../secrets/ftp_username.txt
  ftp_password:
    file: ../secrets/ftp_password.txt